stages:
  data_ingestion:
    cmd: python src/Data_ingestion.py
    deps:
    - src/Data_ingestion.py
    outs:
    - RAW_DATA/Raw/df_test.csv
    - RAW_DATA/Raw/df_train.csv
    params:
    - data_ingestion

  data_preprocessing:
    cmd: python src/Data_preprocessing.py
    deps:
    - RAW_DATA/Raw/df_test.csv
    - RAW_DATA/Raw/df_train.csv
    - src/data_preprocessing.py
    outs:
    - RAW_DATA/df_clean.csv
    params:
    - data_preprocessing

    
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - Raw_data/df_clean.csv
    - Raw_data/df_clean.csv
    - src/feature_engineering.py
    outs:
    - RAW_DATA/Clearn_data/X_train.csv
    - RAW_DATA/Clearn_data/X_test.csv
    - RAW_DATA/Clearn_data/y_train.csv
    - RAW_DATA/Clearn_data/y_test.csv
    params:
    - feature_engineering

  model_trainning:
    cmd: python src/model_trainning.py
    deps:
    - RAW_DATA/Clearn_data/X_train.csv
    - RAW_DATA/Clearn_data/X_test.csv
    - src/model_trainning.py
    outs:
    - Models/model.pkl
    params:
    - model_trainning
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - Models/model.pkl
    - RAW_DATA/Clearn_data/y_test.csv
    - RAW_DATA/Clearn_data/X_test.csv
    - src/model_evaluation.py
    outs:
    - report/metrics.json
    params:
    - model_evaluation
  model_registry:
    cmd: python src/model_registry.py
    deps:
    - report/experiment_info.json
    - src/model_registry.py
    params:
    - model_registry
