data_ingestion:
  bucket_name: viveik-bucket
  folder_path: Loan_Default_Prediction_Evaluation_Criteria 
  file_name: Dataset.csv
  #version_id: kBKfHLm3JVPnRHHr2zU8raEoCMrJbiYZ
  Key: Loan_Default_Prediction_Evaluation_Criteria/Dataset.csv
  aws_access_key_id: AKIAVRNDDVLTW4TLQCUD
  aws_secret_access_key: gSXQxV0j5Zva+FqIvZB4ZWK1/MaSPxkKO7m/X83B
  region_name: eu-north-1 
  test_size: 0.2
  output_path: Raw_DATA/Dataset.csv
  #source_url: "https://example.com/dataset.zip"
  #local_dir: "Raw_data/Raw"

data_preprocessing:
  lowercase: true
  max_len: 250

feature_engineering:
  ngram_range: [1, 2]
  max_features: 10000
  

model_trainning:
  model_type: "RandomForestClassifier"
  test_size: 0.2
  random_state: 42
  n_estimators: 100

model_evaluation:
  #threshold: 0.5
  metrics_output: "report/metrics.json"
 


model_registry:
  registry_path: "report/experiment_info.json"
  model_name: "loan-default-model"
  # Optional: Add tracking URI configuration
  # tracking_uri: "http://127.0.0.1:5000"

