artifact_uri: file:///D:/Loan_defaultor_detection/Loan-Default-Prediction-and-Evaluation-Criteria/remote_server_uri/565587775519539791/c48aa604e1b847b7a9260c455f8b4a15/artifacts
end_time: 1766990548031
entry_point_name: ''
experiment_id: '565587775519539791'
lifecycle_stage: active
run_id: c48aa604e1b847b7a9260c455f8b4a15
run_name: gentle-pig-8
source_name: ''
source_type: 4
source_version: ''
start_time: 1766990535475
status: 3
tags: []
user_id: vivei
