artifact_location: file:///D:/Loan_defaultor_detection/Loan-Default-Prediction-and-Evaluation-Criteria/remote_server_uri/565587775519539791
creation_time: 1766990533056
experiment_id: '565587775519539791'
last_update_time: 1766990533056
lifecycle_stage: active
name: Loan-defaulter-prediction-evaluation
