artifact_location: file:///D:/Loan_defaultor_detection/Loan-Default-Prediction-and-Evaluation-Criteria/remote_server_uri/0
creation_time: 1766990533018
experiment_id: '0'
last_update_time: 1766990533018
lifecycle_stage: active
name: Default
